@startuml

abstract class KalturaPlayer {
    partnerId: Int
    ks: String
    preferredFormat: dash/hls/mp4/wvm
    useStaticMediaProvider: Bool
    serverUrl: String
    referrer: String
    
    autoPlay: Bool
    autoPrepare: Bool
    startPosition: Double
    view: View
    mediaEntry: PKMediaEntry
    
    Player player
    --
    init(partnerId, ks, pluginConfigs, options)
    
    **abstract** initializeBackendComponents()
    **abstract** registerPlugins()
    **abstract** getDefaultServerUrl()
    **abstract** addKalturaPluginConfigs()
    
    setMedia(mediaEntry)
    prepare()
    
}

class KalturaOvpPlayer extends KalturaPlayer {
    loadMedia(entryId)
}

class KalturaPhoenixPlayer extends KalturaPlayer {

}

@enduml
