@startuml

participant App as app
participant KalturaPlayer as player
participant PlayKitPlayer as pkPlayer
participant OvpMediaProvider as provider

app -> player: init(partnerId, ks, options)

note over player
    **Options:**
    //autoPlay//: play when media is ready
    //autoPrepare//: prepare after provider load
    //useStaticMediaProvider//: skip the provider
    //preferredFormat//: dash, hls, mp4, wvm
    //serverUrl//: for on-prem or tests
    //referrer//: for apps with referrer access control
end note

== App wants to load and auto-play an entry ==

app->player: autoPlay=true
app->player: autoPrepare=true

app->player: loadMedia(entryId)

player->provider: load(entryId)
alt success
    provider-->player: entry
    player-->app: entry
    note over player: Keep the entry
    player->pkPlayer: prepare(entry)
    player->pkPlayer: play()
else Load fail
    provider-->player: error
    player-->app: error
end

== App wants to load an entry but play manually ==

app->player: autoPlay=false
app->player: autoPrepare=false

app->player: loadMedia(entryId)
player->provider: load(entryId)
alt success
    provider-->player: entry
    player-->app: entry
    ...
    app->player: prepare()
    app->player: play()
else Load fail
    provider-->player: error
    player-->app: error
end

== Variant: autoPrepare=true, autoPlay=false ==

note over player: prepare media after loaded from provider, but don't auto-play

app->player: autoPlay=false
app->player: autoPrepare=true

app->player: loadMedia(entryId)
...
player->pkPlayer: prepare(entry)
...
app->player: play()

== Variant: autoPrepare=false, autoPlay=true ==

note over player: don't prepare the media until app calls prepare; after prepare, auto-play

app->player: autoPlay=true
app->player: autoPrepare=false

app->player: loadMedia(entryId)
...
app->player: prepare()
player->pkPlayer: prepare(entry)
player->pkPlayer: play()

== Variant: set media without using provider ==

app->player: setMedia(pkMediaEntry)
note over player: player acts according to autoPlay and autoPrepare flags

alt autoPrepare is false
    app->player: prepare()
end

alt autoPlay is false
    app->player: play()
end

== Variant: set start position ==

app->player: startPosition=50

note over player 
    startPosition must be set before prepare is called, so if autoPrepare is true, 
    it must be done before loadMedia/setMedia.
end note

@enduml
